version: '3.7'
services:
  app:
    container_name: accountService
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    image: 'laravelapp'
    ports:
      - 8888:80
    links:
      - accDb
      - rabbitmq
    volumes:
      - .:/var/www/html/laravelMS/ezKartAccService
    networks:
    - internal-network

  accDb:
    container_name: accDb
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - myvolume:/var/lib/mysql
    networks:
    - internal-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: accDb
    depends_on:
        - accDb
    networks:
    - internal-network

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
    - 5672:5672
    - 25672:15672
    volumes:
    - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
    - internal-network

volumes:
  myvolume:
    driver: local

networks:
  internal-network:
    driver: bridge
